### ISSUE TITLE
Related publications

### ISSUE THREAD

**Issue by akash-isu** [ytopt-team/ytopt#14]
It would be great if publications associated with ytopt could be linked in the Readme.

**Comment by jke513** [comment]
Please check out the following paper: https://ieeexplore.ieee.org/document/9307884 and https://www.osti.gov/biblio/1829513-autotuning-polybench-benchmarks-llvm-clang-polly-loop-optimization-pragmas-using-bayesian-optimization  .

**Comment by jke513** [comment]
@akash-isu, the related publications are added to README. Thank you.
