### ISSUE TITLE
Running in parallel

### ISSUE THREAD

**Issue by Sameeranjoshi** [ytopt-team/ytopt#40]
I am using `ytopt` for running a few thousand sampling tests. I want to know if there is any way to run them in parallel or speed up the searching somehow.

I have inputs such that almost 60% of sampling inputs are false positives, so even reducing them from the total sampling space would also be another pointer I wish to know if any.
I tried to use the `conditionals `and `forbidden` but they don't seem to be applicable for the use case which I am trying to get working, my usecase is that I want to keep the multiplication of `tx * ty` which are 2 integer hyperparameters below 1024 which refers to the` threadIdx.x` and` threadIdx.y `which should be less than 1024 the total thread limit on a GPU, any suggestions would be helpful.

Thanks

**Comment by wuxf99** [comment]
Sorry for the late response. Yes, you can try our latest development https://github.com/ytopt-team/ytopt-libensemble to run them in parallel to speed up the search and evaluation processes. For your case, you can add the constraint in your parameter configuration space to make sure x * y < 1024 using LessThanCondition.

**Comment by nchristensen** [comment]
@Sameeranjoshi See https://github.com/automl/ConfigSpace/pull/280 for an implementation of this functionality .

**Comment by wuxf99** [comment]
Thanks
